apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: ubio
spec:
  replicas: 6
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
    
      nodeSelector:
        env: dev  
      containers:
      - name: my-app
        image: rukevweubio/my-terraform-image:latest 
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
